"""Generate the jump anim nodes: media/AnimSets/player/<state>/SourceMoveJump*.xml.

One node per held-weapon type (the clip vanilla's climbfence/vaultOverSprint*.xml picks), in every action
state where Source movement drives the player (Mover.OWNED_STATES), so a jump shows the leap whatever state
it starts in. Each comes as an A/B pair selected by SMJumpAlt, which the mod flips on every takeoff: a
back-to-back hop then enters the other node from the start instead of re-entering one still blending out
with its clip already finished.

Run: python tools/gen_jump_anims.py
"""
import os
import shutil
import uuid

ROOT = os.path.join(os.path.dirname(__file__), '..', 'mod', 'ViewpointSourceMovement', '42', 'media', 'AnimSets', 'player')
STATES = ['idle', 'movement', 'run', 'sprint', 'strafe', 'aim', 'aim-sneak', 'aim-strafe', 'turning',
          'turningAim180', 'turningIdle180', 'turningMovement180', 'slowidleblend']
# suffix, Weapon variable value (None = any), clip
VARIANTS = [
    ('', None, 'Bob_ValultOver_Sprint'),
    ('_1handed', '1Handed', 'Bob_ValultOver_Sprint'),
    ('_2handed', '2handed', 'Bob_ValultOver_Sprint_Bat'),
    ('_spear', 'spear', 'Bob_ValultOver_Sprint_Bat'),
    ('_firearm', 'firearm', 'Bob_ValultOver_Sprint_Rifle'),
    ('_handgun', 'handgun', 'Bob_ValultOver_Sprint_Hgun'),
    ('_heavy', 'heavy', 'Bob_ValultOver_Sprint_2H_heavy'),
]


def cond(name, typ, value):
    xid = uuid.uuid5(uuid.NAMESPACE_URL, 'SourceMoveJump/' + name)
    return ('\t<m_Conditions x_name="%s">\n\t\t<m_Name>%s</m_Name>\n\t\t<m_Type>%s</m_Type>\n'
            '\t\t<m_Value>%s</m_Value>\n\t</m_Conditions>\n') % (xid, name, typ, value)


def node(name, clip, weapon, alt):
    s = ('<?xml version="1.0" encoding="utf-8"?>\n'
         '<!-- Source Movement: the sprinting fence leap while airborne from a jump. Generated by tools/gen_jump_anims.py.\n'
         '     SMJump is set on takeoff and cleared on landing; SMJumpAlt flips every takeoff (A/B nodes, so a quick\n'
         '     re-jump restarts the clip); SMJumpSpeed stretches the clip over the airtime.\n'
         '     No events: the mod plays its own sounds, and vault events would toggle collision. -->\n'
         '<animNode>\n'
         '\t<m_Name>%s</m_Name>\n'
         '\t<m_ConditionPriority>100</m_ConditionPriority>\n'
         '\t<m_AnimName>%s</m_AnimName>\n'
         '\t<m_Looped>false</m_Looped>\n'
         '\t<m_BlendTime>0.08</m_BlendTime>\n'
         '\t<m_BlendOutTime>0.20</m_BlendOutTime>\n'
         '\t<m_SpeedScale>SMJumpSpeed</m_SpeedScale>\n') % (name, clip)
    s += cond('SMJump', 'BOOL', 'true')
    s += cond('SMJumpAlt', 'BOOL', 'true' if alt else 'false')
    if weapon:
        s += cond('Weapon', 'STRING', weapon)
    return s + '</animNode>\n'


def main():
    count = 0
    for state in STATES:
        d = os.path.join(ROOT, state)
        if os.path.isdir(d):
            shutil.rmtree(d)
        os.makedirs(d)
        for suffix, weapon, clip in VARIANTS:
            for alt in (False, True):
                name = 'SourceMoveJump%s%s' % (suffix, '_B' if alt else '')
                with open(os.path.join(d, name + '.xml'), 'w', encoding='utf-8', newline='\r\n') as f:
                    f.write(node(name, clip, weapon, alt))
                count += 1
    print('wrote %d anim nodes in %d states' % (count, len(STATES)))


if __name__ == '__main__':
    main()
